FROM basic-workspace

ARG WORKSPACE_USER
USER ${WORKSPACE_USER}

RUN sudo apt install -y build-essential

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
ENV PATH="/home/${WORKSPACE_USER}/.cargo/bin:${PATH}"
RUN rustup component add rust-src rust-analyzer
RUN sudo ln -s $(rustup which rust-analyzer) /usr/local/bin/rust-analyzer

COPY ./3_rust/languages.toml "/home/${WORKSPACE_USER}/.config/helix/languages.toml"
