FROM basic-workspace

ARG WORKSPACE_USER
USER ${WORKSPACE_USER}

RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
  sudo dpkg -i packages-microsoft-prod.deb && \
  rm packages-microsoft-prod.deb && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-7.0