name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGE_TOKEN }}
    - name: Build the Docker image
      run: cat build.sh | sed -e 's/$USER/$GITHUB_REPOSITORY_OWNER/' | DOCKER_BUILDKIT=1 bash
    - name: Publish to GHCR
      run: bash publish.sh
