FROM basic-workspace

ARG WORKSPACE_USER
USER ${WORKSPACE_USER}

ENV NVM_DIR /home/${WORKSPACE_USER}/.nvm
ENV NODE_VERSION 16

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash && \
    . $NVM_DIR/nvm.sh && \
    nvm install $NODE_VERSION && \
    nvm alias default $NODE_VERSION && \
    nvm use default && \
    npm install -g pnpm npm-check-updates npkill
